#include <QtTest>
#include <QBuffer>
#include <QCryptographicHash>
#include <QDataStream>
#include <QFile>
#include <QtEndian>
#include <algorithm>
#include <array>
#include <cstring>
#include "canon/discoveryengine.h"
#include "canon/pmrreader.h"
#include "canon/pmrreaderalternative.h"

namespace
{
using Outcome = Canon::ParsedSource::Outcome;

// Captured layout, not generated by either reader: v8, one record, arbitrary
// binary IDs, a one-byte filename, empty project, uint32 modification word.
QByteArray sample()
{
	return QByteArray::fromHex("a90700000800000001000000") + QByteArray(32, 'f') +
		QByteArray::fromHex("0100780000") + QByteArray(32, 'm') + QByteArray::fromHex("78563412");
}
QByteArray emptyUnicodeSet() { return QByteArray::fromHex("1000000000000000"); }

Canon::ParsedSource parse(const Canon::SourceReader &reader, QByteArray bytes)
{
	QBuffer source(&bytes);
	source.open(QIODevice::ReadOnly);
	Canon::Cancellation cancellation;
	return reader.read(source, {{}, cancellation});
}

void locator(QDataStream &stream, const Canon::PropertyLocator &value)
{
	stream << value.name << value.key << value.objectNumber << qint64(value.ranges.size());
	for (const auto &range : value.ranges) stream << range.offset << range.length;
}
void properties(QDataStream &stream, const QVector<Canon::RawProperty> &values)
{
	stream << qint64(values.size());
	for (const auto &value : values)
	{
		locator(stream, value.locator);
		stream << value.encoding << value.decoded << qint32(value.state) << value.bytesRetained
			<< (value.textEncoding ? qint32(*value.textEncoding) : -1)
			<< (value.textEncodingBasis ? qint32(*value.textEncodingBasis) : -1);
	}
}
QByteArray facts(const Canon::ParsedSource &result)
{
	QByteArray bytes;
	QDataStream stream(&bytes, QIODevice::WriteOnly);
	stream << qint32(result.outcome) << qint32(result.container)
		<< result.snapshot->path << result.snapshot->modified << qint32(result.snapshot->source)
		<< qint32(result.snapshot->readState) << qint64(result.recordSets.size());
	for (const auto &set : result.recordSets)
		stream << set.name << (set.pmrFileSet ? qint32(*set.pmrFileSet) : -1)
			<< set.version << set.declaredCount << set.objects << set.framingComplete;
	stream << qint64(result.objects.size());
	for (const auto &object : result.objects)
	{
		stream << object.handle << qint32(object.role) << object.recordedIdentity << object.identityEncoding
			<< (object.snapshot == result.snapshot);
		properties(stream, object.properties);
	}
	stream << qint64(result.relationships.size());
	for (const auto &relationship : result.relationships)
	{
		stream << relationship.origin << relationship.target << relationship.recordedReference
			<< relationship.referenceEncoding << qint32(relationship.basis);
		locator(stream, relationship.locator);
	}
	properties(stream, result.unownedProperties);
	// Human explanations/diagnostic wording differ by design, and are reviewed
	// separately. All typed facts, original bytes, ordering and ranges are compared.
	return QCryptographicHash::hash(bytes, QCryptographicHash::Sha256).toHex();
}

class ControlledDevice final : public QIODevice
{
public:
	explicit ControlledDevice(QByteArray bytes) : m_bytes(std::move(bytes))
	{
		open(QIODevice::ReadOnly | QIODevice::Unbuffered);
	}
	Canon::Cancellation *cancelAtEnd = nullptr;
	bool stall = false;
	bool growAtEnd = false;
	bool failSeek = false;
	bool invalidExtent = false;
	mutable int sizeQueries = 0;
	qint64 bytesRead = 0;

	bool isSequential() const override { return false; }
	bool atEnd() const override { return m_cursor == m_bytes.size(); }
	qint64 size() const override { ++sizeQueries; return invalidExtent ? -1 : m_bytes.size(); }
	bool seek(qint64 offset) override
	{
		if (failSeek || offset < 0 || offset > m_bytes.size()) return false;
		m_cursor = offset;
		return QIODevice::seek(offset);
	}
protected:
	qint64 readData(char *data, qint64 maximum) override
	{
		if (stall) return 0;
		const qint64 count = std::min(maximum, qint64(m_bytes.size()) - m_cursor);
		std::memcpy(data, m_bytes.constData() + m_cursor, size_t(count));
		m_cursor += count;
		bytesRead += count;
		if (m_cursor == m_bytes.size())
		{
			if (cancelAtEnd) cancelAtEnd->cancel();
			if (growAtEnd) { m_bytes += emptyUnicodeSet(); growAtEnd = false; }
		}
		return count;
	}
	qint64 writeData(const char *, qint64) override { return -1; }
private:
	QByteArray m_bytes;
	qint64 m_cursor = 0;
};

QStringList fixturePaths()
{
	const QString root = QStringLiteral(FIXTURES_DIR "/");
	return {root + "msmFMID.pmr", root + "corpus_headers/msmFMID.pmr",
		root + "corpus_headers/msmFMID_round3.pmr", root + "omf/avid_supporting/msmFMID.pmr",
		root + "omf/mc2026_audio/msmFMID.pmr"};
}
}

class TestCanonPmrComparison final : public QObject
{
	Q_OBJECT
private slots:
	void identicalFactsOnStaticInputs();
	void everyByteReadFailureRetainsPartialEvidence();
	void finalReadCancellation();
	void sourceGrowsDuringRead();
	void stalledDevice();
	void invalidDeviceAndPreCancellation();
	void realSources();
	void benchmark_data();
	void benchmark();
};

void TestCanonPmrComparison::identicalFactsOnStaticInputs()
{
	const Canon::PmrReader first;
	const Canon::PmrReaderAlternative second;
	const QByteArray complete = sample() + emptyUnicodeSet();
	for (qsizetype size = 0; size <= complete.size(); ++size)
		QCOMPARE(facts(parse(first, complete.first(size))), facts(parse(second, complete.first(size))));
	qsizetype cases = complete.size() + 1;
	// Systematic mutations cover signatures, versions, counts, every identity/text
	// byte, framing words and timestamps. No reader's output is the format oracle.
	for (qsizetype offset = 0; offset < complete.size(); ++offset)
		for (const auto byte : {0x00, 0x01, 0x7f, 0x80, 0xff})
		{
			QByteArray changed = complete;
			changed[offset] = char(byte);
			QVERIFY2(facts(parse(first, changed)) == facts(parse(second, changed)),
				qPrintable(QStringLiteral("Fact difference at byte %1, mutation %2").arg(offset).arg(byte)));
			++cases;
		}
	qInfo() << "Static input fact comparisons:" << cases;
}

void TestCanonPmrComparison::everyByteReadFailureRetainsPartialEvidence()
{
	// Vary actual EOF through a second nonempty set, checking retained evidence
	// against the physical source, not just agreement between implementations.
	QByteArray bytes = sample();
	bytes += QByteArray::fromHex("1000000001000000") + QByteArray(32, 'u') +
		QByteArray::fromHex("04000000c39f0000") + QByteArray(32, 'v') + QByteArray(4, '\0');
	const Canon::PmrReaderAlternative reader;
	for (qsizetype size = 0; size < bytes.size(); ++size)
	{
		const auto result = parse(reader, bytes.first(size));
		QVERIFY(result.outcome == Outcome::Incomplete || size == sample().size());
		QVector<Canon::RawProperty> all = result.unownedProperties;
		for (const auto &object : result.objects) all += object.properties;
		for (const auto &property : all)
			for (const auto &range : property.locator.ranges)
			{
				QVERIFY(range.offset >= 0 && range.length >= 0 && range.offset + range.length <= size);
				if (property.bytesRetained) QCOMPARE(property.encoding, bytes.mid(range.offset, range.length));
			}
	}
}

void TestCanonPmrComparison::finalReadCancellation()
{
	const Canon::PmrReader first;
	const Canon::PmrReaderAlternative second;
	for (const auto *reader : std::array<const Canon::SourceReader *, 2>{&first, &second})
	{
		Canon::Cancellation cancellation;
		ControlledDevice source(sample());
		source.cancelAtEnd = &cancellation;
		const auto result = reader->read(source, {{}, cancellation});
		QVERIFY(cancellation.cancelled());
		QCOMPARE(result.outcome, reader == &first ? Outcome::Complete : Outcome::Cancelled);
		QCOMPARE(result.objects.size(), 1);
		qInfo() << (reader == &first ? "First" : "Alternative") << "final-read cancellation outcome" << int(result.outcome);
	}
}

void TestCanonPmrComparison::sourceGrowsDuringRead()
{
	const Canon::PmrReader first;
	const Canon::PmrReaderAlternative second;
	for (const auto *reader : std::array<const Canon::SourceReader *, 2>{&first, &second})
	{
		Canon::Cancellation cancellation;
		ControlledDevice source(sample());
		source.growAtEnd = true;
		const auto result = reader->read(source, {{}, cancellation});
		QCOMPARE(result.outcome, reader == &first ? Outcome::Complete : Outcome::Incomplete);
		if (reader == &second) QCOMPARE(source.bytesRead, sample().size());
		qInfo() << (reader == &first ? "First" : "Alternative") << "growing-source outcome" << int(result.outcome);
	}
}

void TestCanonPmrComparison::stalledDevice()
{
	const Canon::PmrReader first;
	const Canon::PmrReaderAlternative second;
	for (const auto *reader : std::array<const Canon::SourceReader *, 2>{&first, &second})
	{
		Canon::Cancellation cancellation;
		ControlledDevice source(sample());
		source.stall = true;
		const auto result = reader->read(source, {{}, cancellation});
		QCOMPARE(result.outcome, reader == &first ? Outcome::Incomplete : Outcome::IoError);
		QCOMPARE(source.bytesRead, 0);
	}
}

void TestCanonPmrComparison::invalidDeviceAndPreCancellation()
{
	const Canon::PmrReaderAlternative reader;
	Canon::Cancellation cancellation;
	ControlledDevice source(sample());
	source.invalidExtent = true;
	QCOMPARE(reader.read(source, {{}, cancellation}).outcome, Outcome::IoError);
	QCOMPARE(source.bytesRead, 0);
	source.invalidExtent = false;
	source.failSeek = true;
	QCOMPARE(reader.read(source, {{}, cancellation}).outcome, Outcome::IoError);
	cancellation.cancel();
	const int before = source.sizeQueries;
	QCOMPARE(reader.read(source, {{}, cancellation}).outcome, Outcome::Cancelled);
	QCOMPARE(source.sizeQueries, before);
}

void TestCanonPmrComparison::realSources()
{
	QStringList paths = fixturePaths();
	paths += qEnvironmentVariable("MEDIAMUSTER_CANON_PMR_FILES").split(';', Qt::SkipEmptyParts);
	const QString roots = qEnvironmentVariable("MEDIAMUSTER_CANON_REAL_SCAN_ROOTS");
	if (!roots.isEmpty())
	{
		Canon::Cancellation cancellation;
		const auto scan = Canon::DiscoveryEngine{}.discover({roots.split(';', Qt::SkipEmptyParts), true}, cancellation);
		QVERIFY(scan.discoveryComplete);
		for (const auto &candidate : scan.candidates)
			if (candidate.hint == Canon::SourceCandidate::ReaderHint::Pmr) paths.append(candidate.path);
	}
	const Canon::PmrReader first;
	const Canon::PmrReaderAlternative second;
	qsizetype objects = 0;
	for (const auto &path : paths)
	{
		QFile file(path);
		QVERIFY2(file.open(QIODevice::ReadOnly), qPrintable(path));
		const QByteArray bytes = file.readAll(); // Test corpus only, identical input for both readers.
		const auto a = parse(first, bytes);
		const auto b = parse(second, bytes);
		QVERIFY2(a.outcome == Outcome::Complete && b.outcome == Outcome::Complete, qPrintable(path));
		QVERIFY2(facts(a) == facts(b), qPrintable(path));
		objects += b.objects.size();
		qInfo().noquote() << "MATCH" << QCryptographicHash::hash(bytes, QCryptographicHash::Sha256).toHex()
			<< "records=" << b.objects.size() << path;
	}
	qInfo() << "Real sources compared:" << paths.size() << "records per reader:" << objects;
}

void TestCanonPmrComparison::benchmark_data()
{
	QTest::addColumn<bool>("alternative");
	QTest::newRow("first") << false;
	QTest::newRow("alternative") << true;
}
void TestCanonPmrComparison::benchmark()
{
	if (!qEnvironmentVariableIsSet("MEDIAMUSTER_CANON_PMR_BENCHMARK"))
		QSKIP("Opt-in parsing benchmark; excludes discovery and filesystem I/O.");
	QFETCH(bool, alternative);
	QVector<QByteArray> corpus;
	for (const auto &path : fixturePaths())
	{
		QFile source(path);
		QVERIFY(source.open(QIODevice::ReadOnly));
		corpus.append(source.readAll());
	}
	const Canon::PmrReader first;
	const Canon::PmrReaderAlternative second;
	const Canon::SourceReader &reader = alternative ? static_cast<const Canon::SourceReader &>(second) : first;
	qsizetype records = 0;
	QBENCHMARK
	{
		records = 0;
		for (const auto &bytes : corpus) records += parse(reader, bytes).objects.size();
	}
	QCOMPARE(records, 1756);
}
QTEST_GUILESS_MAIN(TestCanonPmrComparison)
#include "tst_canonpmrcomparison.moc"
