#include <QtTest>
#include <QBuffer>
#include <QCryptographicHash>
#include <QFile>
#include <QSet>
#include <algorithm>
#include <cstring>
#include "mediaengine/discoveryengine.h"
#include "mediaengine/pmrreader.h"

namespace
{
using Outcome = MediaEngine::ParsedSource::Outcome;

// Captured layout, not generated by either reader: v8, one record, arbitrary
// binary IDs, a one-byte filename, empty project, uint32 modification word.
QByteArray sample()
{
	return QByteArray::fromHex("a90700000800000001000000") + QByteArray(32, 'f') +
		QByteArray::fromHex("0100780000") + QByteArray(32, 'm') + QByteArray::fromHex("78563412");
}
QByteArray emptyUnicodeSet() { return QByteArray::fromHex("1000000000000000"); }

MediaEngine::ParsedSource parse(const MediaEngine::SourceReader &reader, QByteArray bytes)
{
	QBuffer source(&bytes);
	source.open(QIODevice::ReadOnly);
	MediaEngine::Cancellation cancellation;
	return reader.read(source, {{}, cancellation});
}

// These invariants compare evidence with the actual input, including malformed
// and truncated sources. A second implementation is not the correctness oracle.
void verifyEvidence(const MediaEngine::ParsedSource &result, const QByteArray &bytes)
{
	QVERIFY(result.snapshot);
	QVERIFY(result.outcome != Outcome::NotRead);
	QSet<MediaEngine::ObjectHandle> handles;
	QVector<MediaEngine::RawProperty> properties = result.unownedProperties;
	for (const auto &object : result.objects)
	{
		QVERIFY(object.handle != 0 && !handles.contains(object.handle));
		handles.insert(object.handle);
		QCOMPARE(object.snapshot, result.snapshot);
		properties += object.properties;
	}
	QSet<MediaEngine::ObjectHandle> members;
	for (const auto &set : result.recordSets)
		for (const auto handle : set.objects)
		{
			QVERIFY(handles.contains(handle) && !members.contains(handle));
			members.insert(handle);
		}
	QCOMPARE(members, handles);
	for (const auto &property : properties)
	{
		QByteArray recorded;
		for (const auto &range : property.locator.ranges)
		{
			QVERIFY(range.offset >= 0 && range.offset <= bytes.size());
			QVERIFY(range.length >= 0 && range.length <= bytes.size() - range.offset);
			recorded += bytes.mid(range.offset, range.length);
		}
		if (property.bytesRetained) QCOMPARE(property.encoding, recorded);
	}
	for (const auto &relationship : result.relationships)
	{
		QVERIFY(handles.contains(relationship.origin));
		QCOMPARE(relationship.target, MediaEngine::ObjectHandle(0)); // PMR stores references, not master objects.
		QByteArray recorded;
		for (const auto &range : relationship.locator.ranges)
		{
			QVERIFY(range.offset >= 0 && range.offset <= bytes.size());
			QVERIFY(range.length >= 0 && range.length <= bytes.size() - range.offset);
			recorded += bytes.mid(range.offset, range.length);
		}
		QCOMPARE(relationship.recordedReference.toByteArray(), recorded);
	}
}

class ControlledDevice final : public QIODevice
{
public:
	explicit ControlledDevice(QByteArray bytes) : m_bytes(std::move(bytes))
	{
		open(QIODevice::ReadOnly | QIODevice::Unbuffered);
	}
	MediaEngine::Cancellation *cancelAtEnd = nullptr;
	bool stall = false;
	bool growAtEnd = false;
	bool failSeek = false;
	bool invalidExtent = false;
	mutable int sizeQueries = 0;
	qint64 bytesRead = 0;

	bool isSequential() const override { return false; }
	bool atEnd() const override { return m_cursor == m_bytes.size(); }
	qint64 size() const override { ++sizeQueries; return invalidExtent ? -1 : m_bytes.size(); }
	bool seek(qint64 offset) override
	{
		if (failSeek || offset < 0 || offset > m_bytes.size()) return false;
		m_cursor = offset;
		return QIODevice::seek(offset);
	}
protected:
	qint64 readData(char *data, qint64 maximum) override
	{
		if (stall) return 0;
		const qint64 count = std::min(maximum, qint64(m_bytes.size()) - m_cursor);
		std::memcpy(data, m_bytes.constData() + m_cursor, size_t(count));
		m_cursor += count;
		bytesRead += count;
		if (m_cursor == m_bytes.size())
		{
			if (cancelAtEnd) cancelAtEnd->cancel();
			if (growAtEnd) { m_bytes += emptyUnicodeSet(); growAtEnd = false; }
		}
		return count;
	}
	qint64 writeData(const char *, qint64) override { return -1; }
private:
	QByteArray m_bytes;
	qint64 m_cursor = 0;
};

QStringList fixturePaths()
{
	const QString root = QStringLiteral(FIXTURES_DIR "/");
	return {root + "msmFMID.pmr", root + "corpus_headers/msmFMID.pmr",
		root + "corpus_headers/msmFMID_round3.pmr", root + "omf/avid_supporting/msmFMID.pmr",
		root + "omf/mc2026_audio/msmFMID.pmr"};
}
}

class TestMediaEnginePmrRobustness final : public QObject
{
	Q_OBJECT
private slots:
	void evidenceOnStaticInputs();
	void everyByteReadFailureRetainsPartialEvidence();
	void finalReadCancellation();
	void sourceGrowsDuringRead();
	void stalledDevice();
	void invalidDeviceAndPreCancellation();
	void realSources();
	void benchmark();
};

void TestMediaEnginePmrRobustness::evidenceOnStaticInputs()
{
	const MediaEngine::PmrReader reader;
	const QByteArray complete = sample() + emptyUnicodeSet();
	for (qsizetype size = 0; size <= complete.size(); ++size)
	{
		const auto bytes = complete.first(size);
		verifyEvidence(parse(reader, bytes), bytes);
		if (QTest::currentTestFailed()) return;
	}
	qsizetype cases = complete.size() + 1;
	// Systematic mutations cover signatures, versions, counts, every identity/text
	// byte, framing words and timestamps. All retained evidence must remain faithful.
	for (qsizetype offset = 0; offset < complete.size(); ++offset)
		for (const auto byte : {0x00, 0x01, 0x7f, 0x80, 0xff})
		{
			QByteArray changed = complete;
			changed[offset] = char(byte);
			verifyEvidence(parse(reader, changed), changed);
			if (QTest::currentTestFailed()) return;
			++cases;
		}
	qInfo() << "Static inputs checked against retained evidence:" << cases;
}

void TestMediaEnginePmrRobustness::everyByteReadFailureRetainsPartialEvidence()
{
	// Vary actual EOF through a second nonempty set, checking retained evidence
	// against the physical source, not just agreement between implementations.
	QByteArray bytes = sample();
	bytes += QByteArray::fromHex("1000000001000000") + QByteArray(32, 'u') +
		QByteArray::fromHex("04000000c39f0000") + QByteArray(32, 'v') + QByteArray(4, '\0');
	const MediaEngine::PmrReader reader;
	for (qsizetype size = 0; size < bytes.size(); ++size)
	{
		const auto result = parse(reader, bytes.first(size));
		QCOMPARE(result.outcome, size == sample().size() ? Outcome::Complete : Outcome::Incomplete);
		verifyEvidence(result, bytes.first(size));
		if (QTest::currentTestFailed()) return;
	}
}

void TestMediaEnginePmrRobustness::finalReadCancellation()
{
	MediaEngine::Cancellation cancellation;
	ControlledDevice source(sample());
	source.cancelAtEnd = &cancellation;
	const auto result = MediaEngine::PmrReader{}.read(source, {{}, cancellation});
	QVERIFY(cancellation.cancelled());
	QCOMPARE(result.outcome, Outcome::Cancelled);
	QCOMPARE(result.objects.size(), 1);
	QCOMPARE(result.snapshot->readState, SourceReadState::Incomplete);
	verifyEvidence(result, sample());
}

void TestMediaEnginePmrRobustness::sourceGrowsDuringRead()
{
	MediaEngine::Cancellation cancellation;
	ControlledDevice source(sample());
	source.growAtEnd = true;
	const auto result = MediaEngine::PmrReader{}.read(source, {{}, cancellation});
	QCOMPARE(result.outcome, Outcome::Incomplete);
	QCOMPARE(source.bytesRead, sample().size());
	QCOMPARE(result.snapshot->readState, SourceReadState::Incomplete);
	QVERIFY(!result.diagnostics.isEmpty());
	verifyEvidence(result, sample());
}

void TestMediaEnginePmrRobustness::stalledDevice()
{
	MediaEngine::Cancellation cancellation;
	ControlledDevice source(sample());
	source.stall = true;
	const auto result = MediaEngine::PmrReader{}.read(source, {{}, cancellation});
	QCOMPARE(result.outcome, Outcome::IoError);
	QCOMPARE(source.bytesRead, 0);
	QCOMPARE(result.snapshot->readState, SourceReadState::Unreadable);
}

void TestMediaEnginePmrRobustness::invalidDeviceAndPreCancellation()
{
	const MediaEngine::PmrReader reader;
	MediaEngine::Cancellation cancellation;
	ControlledDevice source(sample());
	source.invalidExtent = true;
	QCOMPARE(reader.read(source, {{}, cancellation}).outcome, Outcome::IoError);
	QCOMPARE(source.bytesRead, 0);
	source.invalidExtent = false;
	source.failSeek = true;
	QCOMPARE(reader.read(source, {{}, cancellation}).outcome, Outcome::IoError);
	cancellation.cancel();
	const int before = source.sizeQueries;
	QCOMPARE(reader.read(source, {{}, cancellation}).outcome, Outcome::Cancelled);
	QCOMPARE(source.sizeQueries, before);
}

void TestMediaEnginePmrRobustness::realSources()
{
	QStringList paths = fixturePaths();
	paths += qEnvironmentVariable("MEDIAMUSTER_MEDIAENGINE_PMR_FILES").split(';', Qt::SkipEmptyParts);
	const QString roots = qEnvironmentVariable("MEDIAMUSTER_MEDIAENGINE_REAL_SCAN_ROOTS");
	if (!roots.isEmpty())
	{
		MediaEngine::Cancellation cancellation;
		const auto scan = MediaEngine::DiscoveryEngine{}.discover({roots.split(';', Qt::SkipEmptyParts), true}, cancellation);
		QVERIFY(scan.discoveryComplete);
		for (const auto &candidate : scan.candidates)
			if (candidate.hint == MediaEngine::SourceCandidate::ReaderHint::Pmr) paths.append(candidate.path);
	}
	const MediaEngine::PmrReader reader;
	qsizetype objects = 0;
	for (const auto &path : paths)
	{
		QFile file(path);
		QVERIFY2(file.open(QIODevice::ReadOnly), qPrintable(path));
		const QByteArray bytes = file.readAll(); // Test corpus only, for checking evidence against source bytes.
		const auto result = parse(reader, bytes);
		QVERIFY2(result.outcome == Outcome::Complete, qPrintable(path));
		verifyEvidence(result, bytes);
		if (QTest::currentTestFailed()) return;
		objects += result.objects.size();
		qInfo().noquote() << "CHECKED" << QCryptographicHash::hash(bytes, QCryptographicHash::Sha256).toHex()
			<< "records=" << result.objects.size() << path;
	}
	qInfo() << "Real sources checked:" << paths.size() << "records:" << objects;
}

void TestMediaEnginePmrRobustness::benchmark()
{
	if (!qEnvironmentVariableIsSet("MEDIAMUSTER_MEDIAENGINE_PMR_BENCHMARK"))
		QSKIP("Opt-in parsing benchmark; excludes discovery and filesystem I/O.");
	QVector<QByteArray> corpus;
	for (const auto &path : fixturePaths())
	{
		QFile source(path);
		QVERIFY(source.open(QIODevice::ReadOnly));
		corpus.append(source.readAll());
	}
	const MediaEngine::PmrReader reader;
	qsizetype records = 0;
	QBENCHMARK
	{
		records = 0;
		for (const auto &bytes : corpus) records += parse(reader, bytes).objects.size();
	}
	QCOMPARE(records, 1756);
}
QTEST_GUILESS_MAIN(TestMediaEnginePmrRobustness)
#include "tst_mediaenginepmrrobustness.moc"
