#include "avideffects.h"

#include <QHash>
#include <QRegularExpression>
#include <QSet>
#include <QStringList>
#include <QVector>

#include <iterator>

namespace
{
	// MARK: - The catalogue
	//
	// Avid Media Composer's effect catalogue: the names Avid writes into a
	// precompute's clip name. 887 effects extracted on 2026-08-20 from a Media
	// Composer 2025.12 install, from three places, all of them shipped data
	// rather than disassembly:
	//   - 191 built-in effects from AEffectInfo.c, by way of the shipped
	//     translation tables (SupportingFiles/International/xml/MCStrings_*.xml,
	//     which record the source file of every string), with each effect's
	//     palette category from libameLibrary's SetEffectInfoFromIdentifier;
	//   - 31 of Avid's own AVX2 plug-in effects (Illusion FX) from MCEffects.avx;
	//   - 665 third-party effects from Default_ExternalDynamicAVX2.xml in the
	//     application's Resources (Boris BCC, Sapphire, NewBlue).
	//
	// This table is the only copy - there is no data file behind it. Refresh it
	// by re-running the extraction against a newer install rather than editing
	// rows by hand.
	//
	// ROW ORDER IS SIGNIFICANT: one name can sit in several palette groups, and
	// lookup() names them in the order they appear here. The three tiers are
	// interleaved for the same reason - this is the order the extraction
	// produced, and it is preserved rather than tidied.
	struct Entry
	{
		const char *name;		  ///< Avid's English display name ("Color Correction").
		const char *category;	  ///< Palette group ("Image", "Timewarp"...).
		const char *tier;		  ///< Built-in, Avid plug-in, or third-party.
		const char *localised[4]; ///< German, Spanish, French, Italian - in that order.
								  ///< `{}` where Avid ships no translation, which is
								  ///< every third-party plug-in and most Illusion FX.
	};

	// UTF-8 literals: the localised names carry accents and umlauts.
	static constexpr Entry kEffects[] = {
		{"Old Style", "Timewarp", "Avid built-in", {"Old Style", "Estilo antiguo", "Style ancien", "Stile precedente"}},
		{"Timewarp", "Timewarp", "Avid built-in", {"Timewarp", "Deformación temporal", "Variation de vitesse", "Timewarp"}},
		{"Pulldown Removal", "Timewarp", "Avid built-in", {"Pull-Down-Entfernung", "Eliminación de pull-down", "Suppression de la compensation", "Rimozione pulldown"}},
		{"Pulldown Insertion", "Timewarp", "Avid built-in", {"Pull-Down-Einfügung", "Inserción de pull-down", "Insertion de la compensation", "Inserimento pulldown"}},
		{"0% To 100%", "Timewarp", "Avid built-in", {"0 % bis 100 %", "0 % a 100 %", "0 % à 100 %", "Da 0% a 100%"}},
		{"100% To 0%", "Timewarp", "Avid built-in", {"100 % bis 0 %", "100 % a 0 %", "100 % à 0 %", "Da 100% a 0%"}},
		{"Reverse Motion", "Timewarp", "Avid built-in", {"Bewegung umkehren", "Invertir movimiento", "Inverser le mouvement", "Inverti movimento"}},
		{"Speed Boost", "Timewarp", "Avid built-in", {"Geschwindigkeits-Boost", "Speed Boost", "Accélération", "Incremento velocità"}},
		{"Speed Bump", "Timewarp", "Avid built-in", {"Speed Bump", "Speed Bump", "Décélération", "Dissuasore di velocità"}},
		{"Trim To Fill", "Timewarp", "Avid built-in", {"Zum Ausfüllen trimmen", "Ajustar hasta rellenar", "Trim to fill", "Taglia per riempire"}},
		{"FluidFilm 2:3 Cadence", "Timewarp", "Avid built-in", {}},
		{"FluidFilm Progressive", "Timewarp", "Avid built-in", {}},
		{"Motion Adapter", "Timewarp", "Avid built-in", {"Bewegungsadapter", "Adaptador de movimiento", "Adaptateur de mouvement", "Motion Adapter"}},
		{"Freeze Frame", "Timewarp", "Avid built-in", {"", "Congelar frame", "Gel d'image", "Congela fotogramma"}},
		{"Picture-In-Picture A", "Alpha", "Avid built-in", {}},
		{"Transformation", "Xpress 3D Effect", "Avid built-in", {}},
		{"Bottom Box", "Box Wipe", "Avid built-in", {"Unteres Feld", "Caja inferior", "Case du bas", "Casella in basso"}},
		{"Left Box", "Box Wipe", "Avid built-in", {"Feld links", "Cuadro de la izquierda", "Case gauche", "Casella sinistra"}},
		{"Bottom Left to Top Right", "Box Wipe", "Avid built-in", {"Unten links bis oben rechts", "De abajo a la izquierda hasta arriba a la derecha", "Inférieur gauche à supérieur droit", "Da in basso a sinistra a in alto a destra"}},
		{"Bottom Right to Top Left", "Box Wipe", "Avid built-in", {"Unten rechts bis oben links", "De abajo a la derecha hasta arriba a la izquierda", "Inférieur droit à supérieur gauche", "Da in basso a destra a in alto a sinistra"}},
		{"Right Box", "Box Wipe", "Avid built-in", {"Feld rechts", "Cuadro derecho", "Case droite", "Casella di destra"}},
		{"Top Box", "Box Wipe", "Avid built-in", {"Obere Box", "Caja superior", "Boîte supérieure", "Casella superiore"}},
		{"Top Left to Bottom Right", "Box Wipe", "Avid built-in", {"Oben links nach unten rechts", "Desde arriba a la izquierda hasta abajo a la derecha", "En haut à gauche jusqu'en bas à droite", "Da angolo superiore sinistro a inferiore destro"}},
		{"Top Right to Bottom Left", "Box Wipe", "Avid built-in", {"Oben rechts nach unten links", "Desde arriba a la derecha hasta abajo a la izquierda", "En haut à droite jusqu'en bas à gauche", "Da angolo superiore destro a inferiore sinistro"}},
		{"Horizontal", "Edge Wipe", "Avid built-in", {}},
		{"Horz Open", "Edge Wipe", "Avid built-in", {"Horz Offen", "Horiz. abierto", "Ouverture horizontale", "Apertura oriz."}},
		{"Vertical", "Edge Wipe", "Avid built-in", {}},
		{"Vert Open", "Edge Wipe", "Avid built-in", {"Vert. öffnen", "Abierto vert.", "Ouverture Verticale", "Apertura vert"}},
		{"Lower Left Diagonal", "Edge Wipe", "Avid built-in", {"Links unten diagonal", "Izquierda inferior diagonal", "Diagonale gauche bas", "Diagonale in basso a sinistra"}},
		{"Lower Right Diagonal", "Edge Wipe", "Avid built-in", {"Rechts unten diagonal", "Derecha inferior diagonal", "Diagonale droite bas", "Diagonale in basso a destra"}},
		{"Upper Left Diagonal", "Edge Wipe", "Avid built-in", {"Oben links diagonal", "Izquierda superior diagonal", "Diagonale gauche supérieure", "Diagonale in alto a sinistra"}},
		{"Upper Right Diagonal", "Edge Wipe", "Avid built-in", {"Oben rechts diagonal", "Derecha superior diagonal", "Diagonale droite supérieure", "Diagonale in alto a destra"}},
		{"Spiral", "Matrix Wipe", "Avid built-in", {"Spirale", "Spiral", "Spirale", "Spirale"}},
		{"Grid", "Matrix Wipe", "Avid built-in", {"Raster", "Cuadrícula", "Grille", "Griglia"}},
		{"One-Way Row", "Matrix Wipe", "Avid built-in", {"Unidirektionale Zeile", "Fila unidireccional", "Rangée simple", "Riga unidirezionale"}},
		{"Speckle", "Matrix Wipe", "Avid built-in", {"Fleck", "Speckle", "Tache", "Speckle"}},
		{"Zig Zag", "Matrix Wipe", "Avid built-in", {"Zickzack", "Zig Zag", "Zigzag", "Zig zag"}},
		{"Horz Open Sawtooth", "Sawtooth Wipe", "Avid built-in", {"Horz Offener Sägezahn", "Diente de sierra horiz. abierto", "Dents de scie ouverture horizontale", "Dente di sega apertura oriz."}},
		{"Horizontal Sawtooth", "Sawtooth Wipe", "Avid built-in", {"Horizontaler Sägezahn", "Diente de sierra horizontal", "Dents de scie horizontales", "Dente di sega orizzontale"}},
		{"Vert Open Sawtooth", "Sawtooth Wipe", "Avid built-in", {"Vert. Offener Sägezahn", "Diente de sierra abierto vert.", "Dents de scie ouverture verticale", "Dente di sega apertura vert"}},
		{"Vertical Sawtooth", "Sawtooth Wipe", "Avid built-in", {"Vertikaler Sägezahn", "Diente de sierra vertical", "Dents de scie verticales", "Dente di sega verticale"}},
		{"4 Corners", "Shape Wipe", "Avid built-in", {"4 Ecken", "4 esquinas", "4 coins", "4 angoli"}},
		{"Center Box", "Shape Wipe", "Avid built-in", {"Feld zentrieren", "Recuadro centro", "Case centrale", "Casella centrale"}},
		{"Circle", "Shape Wipe", "Avid built-in", {"Kreis", "Círculo", "Cercle", "Cerchio"}},
		{"Clock", "Shape Wipe", "Avid built-in", {"Uhr", "Reloj", "Horloge", "Orologio"}},
		{"Diamond", "Shape Wipe", "Avid built-in", {"Raute", "Rombo", "Losange", "Rombo"}},
		{"Ellipse", "Shape Wipe", "Avid built-in", {"Ellipse", "Elipse", "Ellipse", "Ellissi"}},
		{"Horizontal Bands", "Shape Wipe", "Avid built-in", {"Horizontale Streifen", "Bandas horizontales", "Bandes horizontales", "Bande orizzontali"}},
		{"Vertical Blinds", "Shape Wipe", "Avid built-in", {"Vertikale Markise", "Cortinas verticales", "Persiennes verticales", "Punti ciechi verticali"}},
		{"Horizontal Blinds", "Shape Wipe", "Avid built-in", {"Horizontale Markise", "Persianas horizontales", "Persiennes horizontales", "Blinds orizzontali"}},
		{"Chroma Key", "Key", "Avid built-in", {"Chrominanz-Key", "Inserción del croma", "Incrustation en chrominance", "Chiave crominanza"}},
		{"Luma Key", "Key", "Avid built-in", {"Luma-Schlüssel", "Inserción (key) de luma", "Incrustation en luminance", "Chiave luminanza"}},
		{"Rolling Matte", "Title", "Avid built-in", {"Abspielen der Matte", "Máscara de roll", "Masque à défilement vertical", "Mascherino a scorrimento verticale"}},
		{"Crawling Matte", "Title", "Avid built-in", {"Kriechende Matte", "Máscara de crawl", "Masque à défilement horizontal", "Scorrimento orizzontale del mascherino"}},
		{"Matte Key", "Key", "Avid built-in", {"Matte-Key", "Key de máscara", "Cache", "Effetto Matte Key"}},
		{"Matte Key", "Key", "Avid built-in", {"Matte-Key", "Key de máscara", "Cache", "Effetto Matte Key"}},
		{"Dissolve", "Blend", "Avid built-in", {"Blende", "Encadenado", "Fondu", "Dissolvenza"}},
		{"Superimpose", "Blend", "Avid built-in", {"Superimpose", "Superponer", "Surimpression", "Sovrapponi"}},
		{"Film Dissolve", "Film", "Avid built-in", {"Film-Blende", "Película: encadenado", "Enchaîné du film", "Dissolvenza pellicola"}},
		{"Film Fade", "Film", "Avid built-in", {"Film-Fade", "Película: fundido", "Fondu du film", "Fade pellicola"}},
		{"Fade to Color", "Blend", "Avid built-in", {"Fade zu Farbe", "Fundir a color", "Fondu à une couleur", "Dissolvi in colore"}},
		{"Fade from Color", "Blend", "Avid built-in", {"Fade aus Farbe", "Fundir desde color", "Fondu d'une couleur", "Dissolvi da colore"}},
		{"Dip to Color", "Blend", "Avid built-in", {"Übergang zu Farbe", "Fundido a color", "Enchaîner par une couleur", "Dip in colore"}},
		{"Title", "Title", "Avid built-in", {}},
		{"Rolling Title", "Title", "Avid built-in", {"Rolltitel", "Título de roll", "Titre à défilement vertical", "Titolo a scorrimento verticale"}},
		{"Crawling Title", "Title", "Avid built-in", {"Kriechtitel", "Título de crawl", "Titre à défilement horizontal", "Titolo scorrimento orizzontale"}},
		{"Animated Title", "Title", "Avid built-in", {"Animierter Titel", "Título animado", "Titre animé", "Titolo animato"}},
		{"PassThru", "Image", "Avid built-in", {"PassThru", "PassThru", "Passage", "Passthrough"}},
		{"Paint Effect", "Image", "Avid built-in", {"Farbeffekt", "Efecto de pintura", "Effet de peinture", "Effetto disegno"}},
		{"AniMatte", "Key", "Avid built-in", {"AniMatte", "AniMatte", "AniMatte", "AniMatte"}},
		{"Mosaic Effect", "Image", "Avid built-in", {"Mosaik-Effekt", "Efecto de mosaico", "Effet mosaïque", "Effetto mosaico"}},
		{"Spot Color Effect", "Image", "Avid built-in", {"Spot-Farbeffekt", "Efecto Spot Color", "Effet de retouche de couleur", "Effetto colore campione"}},
		{"Scratch Removal", "Image", "Avid built-in", {"Entfernen von Kratzern", "Eliminación de rasguños", "Suppression du bruit de rayure", "Rimozione file temporanei"}},
		{"FluidMotion Edit", "Image", "Avid built-in", {"FluidMotion-Bearbeitung", "Editar FluidMotion", "Montage FluidMotion", "Modifica FluidMotion"}},
		{"Blur Effect", "Image", "Avid built-in", {"Weichzeichnen-Effekt", "Efecto difuminado", "Effet flou", "Effetto sfocato"}},
		{"Submaster", "Image", "Avid built-in", {"Submaster", "Submaster", "Substitut", "Submaster"}},
		{"Color Effect", "Image", "Avid built-in", {"Farbeffekt", "Efecto de color", "Effet colorimétrique", "Effetto colore"}},
		{"Color Correction", "Image", "Avid built-in", {"Farbkorrektur", "Corrección de color", "Correction colorimétrique", "Correzione colore"}},
		{"3D Warp", "Xpress 3D Effect", "Avid built-in", {"3D-Warp", "Deformación 3D", "Distorsion 3D", "Distorsione 3D"}},
		{"3D PIP", "Xpress 3D Effect", "Avid built-in", {"3D-PIP", "PIP 3D", "Image dans l'image 3D", "PIP 3D"}},
		{"3D Page Curl", "Xpress 3D Effect", "Avid built-in", {"3D Page Curl", "Rizo de página 3D", "Enroulement de page 3D", "Arrotolamento pagina 3D"}},
		{"3D Quad Split", "Xpress 3D Effect", "Avid built-in", {"3D-Vierer-Split", "División cuad.3D", "4/4 3D", "Divisione quadrupla 3D"}},
		{"3D Arrow", "Xpress 3D Effect", "Avid built-in", {"3D-Pfeil", "Flecha 3D", "Flèche 3D", "Freccia 3D"}},
		{"3D Slats", "Xpress 3D Effect", "Avid built-in", {"3D-Lamelle", "Tablillas 3D", "Lattes 3D", "Slat 3D"}},
		{"3D Multi Wave", "Xpress 3D Effect", "Avid built-in", {"3D-Multi-Welle", "Multionda 3D", "Multivague 3D", "Multionda 3D"}},
		{"3D Center Burst", "Xpress 3D Effect", "Avid built-in", {"3D-Mitte-Burst", "Golpe centro 3D", "Impulsion centrale 3D", "Burst centro 3D"}},
		{"3D Sine Wave", "Xpress 3D Effect", "Avid built-in", {"3D-Sinuswelle", "Onda sinusoidal 3D", "Sinusoïdale 3D", "Sinusoide 3D"}},
		{"3D Ball", "Xpress 3D Effect", "Avid built-in", {"3D-Kugel", "Bola 3D", "Balle 3D", "Palla 3D"}},
		{"3D Page Fold", "Xpress 3D Effect", "Avid built-in", {"3D Page Fold", "Pliegue de página 3D", "Pli de page 3D", "Piega pagina 3D"}},
		{"3D Bumps", "Xpress 3D Effect", "Avid built-in", {"3D-Erhebungen", "Protuberancias 3D", "Bumps 3D", "3D Bumps"}},
		{"3D Title", "Title", "Avid built-in", {"3D-Titel", "Título 3D", "Titre 3D", "Titolo 3D"}},
		{"3D Matte Key", "Title", "Avid built-in", {"3D-Matte-Key", "Key de máscara 3D", "Cache 3D", "Effetto Matte Key 3D"}},
		{"Symphony Warp", "Xpress 3D Effect", "Avid built-in", {"Symphony Warp", "Symphony Warp", "Distorsion Symphony", "Distorsione Symphony"}},
		{"Ultimatte", "Key", "Avid built-in", {"Ultimatte", "Ultimatte", "Ultimatte", "Ultimatte"}},
		{"Stabilize", "Image", "Avid built-in", {"Stabilisieren", "Estabilizar", "Stabiliser", "Stabilizza"}},
		{"Color Adapter", "Image", "Avid built-in", {"Farbadapter", "Adaptador de color", "Adaptateur de couleur", "Adattatore colore"}},
		{"Color Space", "Image", "Avid built-in", {"Farbraum", "Espacio de color", "Espace colorimétrique", "Spazio colore"}},
		{"Target Color Space", "Image", "Avid built-in", {"Ziel-Farbraum", "Espacio de color de destino", "Espace colorimétrique cible", "Spazio colore di destinazione"}},
		{"Composite", "Alpha", "Avid built-in", {"", "Compuesto", "Composite", "Composito"}},
		{"3D DVE", "Alpha", "Avid built-in", {"", "DVE 3D", "DVE 3D", "DVE 3D"}},
		{"3D Blur", "Alpha", "Avid built-in", {"", "Desenfoque 3D", "Flou 3D", "Sfocatura 3D"}},
		{"3-track Combiner", "Key", "Avid built-in", {"", "Combinador de 3 pistas", "Combinateur 3-track", "Combinatore a 3 tracce"}},
		{"3D 3-track Combiner", "Title", "Avid built-in", {"", "Combinador 3D de 3 pistas", "Combinateur 3-track 3D", "Combinatore a 3 tracce 3D"}},
		{"Combiner", "Alpha", "Avid built-in", {}},
		{"Working Color Space", "Image", "Avid built-in", {}},
		{"Track Composite", "Alpha", "Avid built-in", {}},
		{"3D Crop", "Alpha", "Avid built-in", {}},
		{"3D Spill", "Alpha", "Avid built-in", {}},
		{"3D Color Slide", "Alpha", "Avid built-in", {}},
		{"Avid Color Generator", "Alpha", "Avid built-in", {}},
		{"Composite Adapter", "Alpha", "Avid built-in", {}},
		{"1.66 Mask", "Film", "Avid built-in", {"1,66 Maske", "Máscara de 1,66", "Masque 1,66", "Maschera 1.66"}},
		{"1.85 Mask", "Film", "Avid built-in", {"1,85 Maske", "Máscara de 1,85", "Masque 1,85", "Maschera 1.85"}},
		{"Anamorphic Mask", "Film", "Avid built-in", {"Anamorphotische Maske", "Máscara anamórfica", "Masque anamorphique", "Maschera anamorfica"}},
		{"16:9 Mask", "Film", "Avid built-in", {"16:9 Maske", "Máscara 16:9", "16:9 masque", "Maschera 16:9"}},
		{"Mask", "Film", "Avid built-in", {"Maske", "Máscara", "Masque", "Maschera"}},
		{"Mask", "Image", "Avid built-in", {"Maske", "Máscara", "Masque", "Maschera"}},
		{"Picture-In-Picture", "Blend", "Avid built-in", {"Bild-in-Bild", "Imagen en imagen", "Image dans l'image", "Picture in Picture"}},
		{"Blowup", "Film", "Avid built-in", {"Blow-up", "Ampliación", "Agrandissement", "Ingrandimento"}},
		{"Resize", "Image", "Avid built-in", {"Größe ändern", "Cambiar tamaño", "Redimensionner", "Ridimensiona"}},
		{"Pan and Scan", "Reformat", "Avid built-in", {"Pannen und Scannen", "Pan. y scan", "Pan and Scan", "Pan e scansione"}},
		{"16:9 Letterbox", "Reformat", "Avid built-in", {"16:9 Letterbox", "16:9 apaisado", "16:9 letterbox", "Letterbox 16:9"}},
		{"14:9 Letterbox", "Reformat", "Avid built-in", {"14:9 Letterbox", "14:9 apaisado", "14:9 letterbox", "Letterbox 14:9"}},
		{"4:3 Sidebar", "Reformat", "Avid built-in", {"4:3-Seitenleiste", "Barra lateral 4:3", "4:3 barre latérale", "Barra laterale 4:3"}},
		{"Flip", "Image", "Avid built-in", {"Spiegeln/Umkehren", "Invertir", "Retourner", "Inverti"}},
		{"Flip-Flop", "Image", "Avid built-in", {"Flip-Flop (vert.-hor.)", "Flip-Flop", "Retournement horizontal et vertical", "Inverti-ribalta"}},
		{"Flop", "Image", "Avid built-in", {"Flop (hor.)", "Flop", "Retournement horizontal", "Ribalta"}},
		{"Bottom Left to Top Right", "Conceal", "Avid built-in", {"Unten links bis oben rechts", "De abajo a la izquierda hasta arriba a la derecha", "Inférieur gauche à supérieur droit", "Da in basso a sinistra a in alto a destra"}},
		{"Bottom Right to Top Left", "Conceal", "Avid built-in", {"Unten rechts bis oben links", "De abajo a la derecha hasta arriba a la izquierda", "Inférieur droit à supérieur gauche", "Da in basso a destra a in alto a sinistra"}},
		{"Bottom to Top", "Conceal", "Avid built-in", {"Unten bis oben", "De abajo arriba", "De bas en haut", "Dal basso verso l'alto"}},
		{"Left to Right", "Conceal", "Avid built-in", {"Von links nach rechts", "De izquierda a derecha", "De gauche à droite", "Da sinistra a destra"}},
		{"Right to Left", "Conceal", "Avid built-in", {"Von rechts nach links", "De derecha a izquierda", "De droite à gauche", "Da destra a sinistra"}},
		{"Top Left to Bottom Right", "Conceal", "Avid built-in", {"Oben links nach unten rechts", "Desde arriba a la izquierda hasta abajo a la derecha", "En haut à gauche jusqu'en bas à droite", "Da angolo superiore sinistro a inferiore destro"}},
		{"Top Right to Bottom Left", "Conceal", "Avid built-in", {"Oben rechts nach unten links", "Desde arriba a la derecha hasta abajo a la izquierda", "En haut à droite jusqu'en bas à gauche", "Da angolo superiore destro a inferiore sinistro"}},
		{"Top to Bottom", "Conceal", "Avid built-in", {"Von oben nach unten", "De arriba abajo", "De haut en bas", "Dall'alto verso il basso"}},
		{"Bottom Left", "L-Conceal", "Avid built-in", {"Unten links", "Abajo a la izquierda", "Gauche bas", "In basso a sinistra"}},
		{"Bottom Right", "L-Conceal", "Avid built-in", {"Unten rechts", "Abajo a la derecha", "Droite bas", "In basso a destra"}},
		{"Top Left", "L-Conceal", "Avid built-in", {"Oben links", "Arriba a la izquierda", "En haut à gauche", "In alto a sinistra"}},
		{"Top Right", "L-Conceal", "Avid built-in", {"Oben Rechts", "Arriba a la derecha", "Droite haut", "In alto a destra"}},
		{"Bottom Left Corner", "Peel", "Avid built-in", {"Untere linke Ecke", "Esquina inferior izquierda", "Coin inférieur gauche", "Angolo in basso a sinistra"}},
		{"Bottom Right Corner", "Peel", "Avid built-in", {"Untere rechte Ecke", "Esquina inferior derecha", "Coin inférieur droit", "Angolo in basso a destra"}},
		{"Bottom to Top", "Peel", "Avid built-in", {"Unten bis oben", "De abajo arriba", "De bas en haut", "Dal basso verso l'alto"}},
		{"Left to Right", "Peel", "Avid built-in", {"Von links nach rechts", "De izquierda a derecha", "De gauche à droite", "Da sinistra a destra"}},
		{"Right to Left", "Peel", "Avid built-in", {"Von rechts nach links", "De derecha a izquierda", "De droite à gauche", "Da destra a sinistra"}},
		{"Top Left Corner", "Peel", "Avid built-in", {"Obere linke Ecke", "Esquina superior izquierda", "Coin supérieur gauche", "Angolo in alto a sinistra"}},
		{"Top Right Corner", "Peel", "Avid built-in", {"Obere rechte Ecke", "Esquina superior derecha", "Coin droit supérieur", "Angolo in alto a destra"}},
		{"Top to Bottom", "Peel", "Avid built-in", {"Von oben nach unten", "De arriba abajo", "De haut en bas", "Dall'alto verso il basso"}},
		{"Bottom Left to Top Right", "Push", "Avid built-in", {"Unten links bis oben rechts", "De abajo a la izquierda hasta arriba a la derecha", "Inférieur gauche à supérieur droit", "Da in basso a sinistra a in alto a destra"}},
		{"Bottom Right to Top Left", "Push", "Avid built-in", {"Unten rechts bis oben links", "De abajo a la derecha hasta arriba a la izquierda", "Inférieur droit à supérieur gauche", "Da in basso a destra a in alto a sinistra"}},
		{"Bottom to Top", "Push", "Avid built-in", {"Unten bis oben", "De abajo arriba", "De bas en haut", "Dal basso verso l'alto"}},
		{"Left to Right", "Push", "Avid built-in", {"Von links nach rechts", "De izquierda a derecha", "De gauche à droite", "Da sinistra a destra"}},
		{"Right to Left", "Push", "Avid built-in", {"Von rechts nach links", "De derecha a izquierda", "De droite à gauche", "Da destra a sinistra"}},
		{"Top Left to Bottom Right", "Push", "Avid built-in", {"Oben links nach unten rechts", "Desde arriba a la izquierda hasta abajo a la derecha", "En haut à gauche jusqu'en bas à droite", "Da angolo superiore sinistro a inferiore destro"}},
		{"Top Right to Bottom Left", "Push", "Avid built-in", {"Oben rechts nach unten links", "Desde arriba a la derecha hasta abajo a la izquierda", "En haut à droite jusqu'en bas à gauche", "Da angolo superiore destro a inferiore sinistro"}},
		{"Top to Bottom", "Push", "Avid built-in", {"Von oben nach unten", "De arriba abajo", "De haut en bas", "Dall'alto verso il basso"}},
		{"X Spin", "Spin", "Avid built-in", {"X-Spin", "Giro X", "Rotation X", "Rotazione X"}},
		{"Y Spin", "Spin", "Avid built-in", {"Y-Spin", "Giro Y", "Rotation Y", "Rotazione Y"}},
		{"Z Spin", "Spin", "Avid built-in", {"Z-Spin", "Giro Z", "Rotation Z", "Rotazione Z"}},
		{"Bottom Centered", "Squeeze", "Avid built-in", {"Unten Mitte", "Centrado en la parte inferior", "Centré bas", "In basso al centro"}},
		{"Bottom Left", "Squeeze", "Avid built-in", {"Unten links", "Abajo a la izquierda", "Gauche bas", "In basso a sinistra"}},
		{"Bottom Right", "Squeeze", "Avid built-in", {"Unten rechts", "Abajo a la derecha", "Droite bas", "In basso a destra"}},
		{"Bottom to Top", "Squeeze", "Avid built-in", {"Unten bis oben", "De abajo arriba", "De bas en haut", "Dal basso verso l'alto"}},
		{"Centered Zoom", "Squeeze", "Avid built-in", {"Zentrierter Zoom", "Zoom centrado", "Zoom centré", "Zoom centrato"}},
		{"Horizontal Centered", "Squeeze", "Avid built-in", {"Horizontal zentriert", "Centrado horizontal", "Centré horizontal", "Centrato orizzontalmente"}},
		{"Left Centered", "Squeeze", "Avid built-in", {"Links zentriert", "Centrado a la izquierda", "Centré gauche", "Centrato a sinistra"}},
		{"Left to Right", "Squeeze", "Avid built-in", {"Von links nach rechts", "De izquierda a derecha", "De gauche à droite", "Da sinistra a destra"}},
		{"Right Centered", "Squeeze", "Avid built-in", {"Rechts zentriert", "Centrado a la derecha", "Centré droite", "Centrato a destra"}},
		{"Right to Left", "Squeeze", "Avid built-in", {"Von rechts nach links", "De derecha a izquierda", "De droite à gauche", "Da destra a sinistra"}},
		{"Top Centered", "Squeeze", "Avid built-in", {"Oben zentriert", "Arriba en el centro", "Centré haut", "Centrato in alto"}},
		{"Top Left", "Squeeze", "Avid built-in", {"Oben links", "Arriba a la izquierda", "En haut à gauche", "In alto a sinistra"}},
		{"Top Right", "Squeeze", "Avid built-in", {"Oben Rechts", "Arriba a la derecha", "Droite haut", "In alto a destra"}},
		{"Top to Bottom", "Squeeze", "Avid built-in", {"Von oben nach unten", "De arriba abajo", "De haut en bas", "Dall'alto verso il basso"}},
		{"Vertical Centered", "Squeeze", "Avid built-in", {"Vertikal zentriert", "Vertical en el centro", "Centré vertical", "Centrato verticalmente"}},
		{"FrameFlex", "Reformat", "Avid built-in", {"FrameFlex", "FrameFlex", "FrameFlex", "FrameFlex"}},
		{"2-track Combiner", "", "Avid built-in", {"", "Combinador de 2 pistas", "Combinateur 2-track", "Combinatore a 2 tracce"}},
		{"Box Wipe", "Box Wipe", "Avid built-in", {"Feld-Wischen", "Cortinilla de caja", "Volet carré", "Cancellazione casella"}},
		{"Conceal", "Conceal", "Avid built-in", {"Verdecken", "Ocultar", "Dissimuler", "Nascondi"}},
		{"Edge Wipe", "Edge Wipe", "Avid built-in", {"Kanten-Wischen", "Cortinilla de borde", "Volet droit", "Dissolvenza margine"}},
		{"Film", "Film", "Avid built-in", {"Film", "Cine", "Film", "Pellicola"}},
		{"Image", "Image", "Avid built-in", {"Bild", "Imagen", "Image", "Immagine"}},
		{"Key", "Key", "Avid built-in", {"Key", "Key", "Touche", "Chiave"}},
		{"L-Conceal", "L-Conceal", "Avid built-in", {"L-Conceal", "L-Conceal", "Cacher en L", "Nascondi luminanza"}},
		{"Matrix Wipe", "Matrix Wipe", "Avid built-in", {"Matrix-Wischblende", "Cortinilla de matriz", "Volet de matrice", "Cancellazione matrice"}},
		{"Peel", "Peel", "Avid built-in", {"Peel", "Peel", "Page tournée", "Stacco"}},
		{"Push", "Push", "Avid built-in", {"Push", "Push", "Pousser", "Push"}},
		{"Reformat", "Reformat", "Avid built-in", {"Neuformatierung", "Reformatear", "Reformater", "Riformattazione"}},
		{"Sawtooth Wipe", "Sawtooth Wipe", "Avid built-in", {"Sägezahn-Wischblende", "Cortinilla de diente de sierra", "Volet dents de scie", "Dissolvenza a dente di sega"}},
		{"Shape Wipe", "Shape Wipe", "Avid built-in", {"Form Wischblende", "Cortinilla de forma", "Volet de forme", "Dissolvenza forma"}},
		{"Spin", "Spin", "Avid built-in", {"Spin", "Spin", "Rotation", "Rotazione"}},
		{"Squeeze", "Squeeze", "Avid built-in", {"Stauchen", "Extraer", "Compression", "Espandi"}},
		{"Xpress 3D Effect", "Xpress 3D Effect", "Avid built-in", {"Xpress 3D-Effekt", "Efecto 3D de Xpress", "Effet 3D Xpress", "Effetto Xpress 3D"}},
		{"Color", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Crystal", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Film", "Illusion FX", "Avid plug-in (Illusion FX)", {"Film", "Cine", "Film", "Pellicola"}},
		{"Flare", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"FluidBlur", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"FluidColorMap", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"FluidMorph", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Iris", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Kaleidoscope", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Lightning", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Melt", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Motion", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"PSNR", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Pagecurl", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Particle", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Pattern", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Pinch", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"RGBKeyer", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Radial", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Random", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Region", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Ripple", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Rollup", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Shear", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Sparkler", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Sphere", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Swirl", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Twist", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"Wave", "Illusion FX", "Avid plug-in (Illusion FX)", {}},
		{"S_SwishPan", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_WipeStripes", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_TriTone", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Textured Wipe TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Safe Colors MT", "BCC Color & Tone", "Third-party plug-in", {}},
		{"BCC Title Studio", "BCC 3D Objects", "Third-party plug-in", {}},
		{"S_MatteOpsComp", "Sapphire Composite", "Third-party plug-in", {}},
		{"BCC 3D Extruded ImageShatter TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Sphere", "BCC Perspective", "Third-party plug-in", {}},
		{"BCC Trails Basic", "BCC Time", "Third-party plug-in", {}},
		{"BCC DeGrain OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Wave TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_EdgeAwareBlur", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Radial Wipe TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_FlickerMatch", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Reptilian RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_WarpVortex", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_FlickerRemove", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Cube TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_GrainRemove", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Posterize", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_WipeClock", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Color Match", "BCC Color & Tone", "Third-party plug-in", {}},
		{"BCC Glow Matte OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_ZConvolve", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"S_DissolveGlintRainbow", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Sparkles", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Blobs Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Spotlight", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Super Blend TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rays_Ring MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Film Process OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Sharpen", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Z Space II TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_WarpFishEye", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_Threshold", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC DVE", "BCC Perspective", "Third-party plug-in", {}},
		{"S_DissolveGlint", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Z Space III OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_TextureCells", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Witness Protection", "BCC Match Move", "Third-party plug-in", {}},
		{"BCC Clouds", "BCC Textures", "Third-party plug-in", {}},
		{"EFF_NEWBLUE_TITLE_V2", "Generator", "Avid plug-in (Illusion FX)", {}},
		{"S_Trails", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Noise Map 2", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Mosaic OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Lens Flare Round", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Light Matte TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Misalignment", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Lens Transition OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_AutoPaint", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Optical Flow", "BCC Time", "Third-party plug-in", {}},
		{"BCC Boost Blend TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Cross Melt", "BCC Transitions", "Third-party plug-in", {}},
		{"S_FlutterCut", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_JitterFrames", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Color Match MT", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_EmbossShiny", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Rays_Wedge", "BCC Lights", "Third-party plug-in", {}},
		{"S_MuzzleFlash", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Vector Blur Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Pixel Fixer", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Lens Shape", "BCC Blur", "Third-party plug-in", {}},
		{"S_CloudsMultColor", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Vector Displacement", "BCC Warp", "Third-party plug-in", {}},
		{"S_DissolveZap", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Flashbulbs", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Pin Art 3D", "BCC Particles", "Third-party plug-in", {}},
		{"S_PseudoColor", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_LensFlareAutoTrack", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Linear Wipe OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Checker Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"Timecode Burn-In", "Generator", "Avid plug-in (Illusion FX)", {}},
		{"S_FreezeFrame", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Scatterize", "BCC Stylize", "Third-party plug-in", {}},
		{"S_DistortBlur", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_GlowRings", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Magic Sharp", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Unsharp Mask", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Spraypaint Noise TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Cloth RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Swish3D", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC UpRez", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_EdgeColorize", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_LaserBeam", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Particle Emitter 3D", "BCC Particles", "Third-party plug-in", {}},
		{"BCC Film Glow OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_TextureWeave", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Rectangular Wipe OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_TextureLoops", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Boost Blend OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Tint", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Bump Map", "BCC Art Looks", "Third-party plug-in", {}},
		{"BCC 3D Extruded ImageShatter", "BCC Perspective", "Third-party plug-in", {}},
		{"S_WarpPolar", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_FeedbackDistort", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Linear Luma Key OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_BandPass", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Flicker Fixer", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Particle Emitter 3D MT", "BCC Particles", "Third-party plug-in", {}},
		{"BCC Displacement Map", "BCC Warp", "Third-party plug-in", {}},
		{"BCC Composite", "BCC Key & Blend", "Third-party plug-in", {}},
		{"S_CardFlip", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_DissolveDiffuse", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_DissolveGlare", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Light Sweep MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Z Space II OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Bulge MT", "BCC Warp", "Third-party plug-in", {}},
		{"BCC Color Balance", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_PsykoBlobs", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_SpotLight", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Velocity Remap", "BCC Time", "Third-party plug-in", {}},
		{"BCC Lens Flare 3D", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Fast Flipper OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Lens Blur OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Caustics", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Light Matte OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Film Damage", "BCC Film Style", "Third-party plug-in", {}},
		{"BCC Dust and Scratches", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Rough Glow TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Page Turn", "BCC Perspective", "Third-party plug-in", {}},
		{"S_GradientMulti", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Mixed Colors RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_GradientRadial", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Invert-Solarize OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Damaged TV Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC DVE Basic", "BCC Perspective", "Third-party plug-in", {}},
		{"S_DissolveAutoPaint", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Alpha Spotlight TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Gaussian Blur", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Levels-Gamma OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_TimeWarpRGB", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Film Process OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Star Matte OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Cube", "BCC Perspective", "Third-party plug-in", {}},
		{"S_DistortChroma", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Motion Key", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Two Way Key", "BCC Key & Blend", "Third-party plug-in", {}},
		{"S_MotionDetect", "Sapphire Time", "Third-party plug-in", {}},
		{"S_JpegDamage", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Video Glitch RT", "BCC Stylize", "Third-party plug-in", {}},
		{"S_TextureFlux", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Rock RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Radial Blur", "BCC Blur", "Third-party plug-in", {}},
		{"S_DissolvePuddle", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Film Glow Dissolve OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rays_Radiant Spotlight", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Beauty Studio", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Multitone OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_FieldRemove", "Sapphire Time", "Third-party plug-in", {}},
		{"S_TVDamage", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_TrailsDiffuse", "Sapphire Time", "Third-party plug-in", {}},
		{"S_WarpBubble", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC UpRez DeInt", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_FlysEyeCircles", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Mixed Colors", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Safe Colors", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_WarpTransform", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Multi Stretch Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC RGB Blend OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Layer", "Sapphire Composite", "Third-party plug-in", {}},
		{"S_Invert", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Lens Blur Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"S_Deband", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"S_DissolveEdgeRays", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Invert-Solarize", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_WipeFourWedges", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_GlowDarks", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_KaleidoRadial", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Particle Array 3D TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Film Glow OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC DeNoise OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Colorize MT", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_EmbossGlass", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_WipeDiffuse", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_FlickerRmMatteColor", "Sapphire Time", "Third-party plug-in", {}},
		{"S_InfiniteZoom", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Stage Light TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_DissolveFilm", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Particle Systems MT", "BCC Particles", "Third-party plug-in", {}},
		{"BCC Motion Blur", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Drop Shadow", "BCC Stylize", "Third-party plug-in", {}},
		{"S_WipePlasma", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Radial Blur MT", "BCC Blur", "Third-party plug-in", {}},
		{"BCC 3D Image Shatter OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Make Alpha OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Wood Grain RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_DissolveVortex", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_WipeRectangle", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Rays", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_Sketch", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Extruded EPS", "BCC 3D Objects", "Third-party plug-in", {}},
		{"BCC Z-Blur", "BCC Blur", "Third-party plug-in", {}},
		{"S_CloudsColorSmooth", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Light Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"S_QuadTone", "Sapphire Adjust", "Third-party plug-in", {}},
		{"S_HalfToneRings", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_FlickerRemoveColor", "Sapphire Time", "Third-party plug-in", {}},
		{"S_WipeWeave", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Halftone MT", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_Dissolve", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC DVE Basic TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Colorize Glow", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Edge Light", "BCC Lights", "Third-party plug-in", {}},
		{"S_WipeDoubleWedge", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC 3D Image Shatter TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_GlowAura", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Film Grain", "BCC Film Style", "Third-party plug-in", {}},
		{"BCC Remover", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_NightSky", "Sapphire Render", "Third-party plug-in", {}},
		{"S_ReverseClip", "Sapphire Time", "Third-party plug-in", {}},
		{"S_Streaks", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Ribbon Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Rays_Radiant Edges MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Textured Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Unsharp Mask OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Extruded Text", "BCC 3D Objects", "Third-party plug-in", {}},
		{"BCC Rays_Textured MT", "BCC Lights", "Third-party plug-in", {}},
		{"S_WipeTiles", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Matte Choker", "BCC Key & Blend", "Third-party plug-in", {}},
		{"S_StripSlideTransition", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Rays_Puffy TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Noise Map OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Trails", "BCC Time", "Third-party plug-in", {}},
		{"BCC Water Waves Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Ripple Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"S_Zebrafy", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Sparks", "BCC Particles", "Third-party plug-in", {}},
		{"BCC Edge Grunge", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Wood Grain", "BCC Textures", "Third-party plug-in", {}},
		{"S_DistortRGB", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_LensFlare", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Lens Blur OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Fractal Noise RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_WipeCells", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Fast Lens Blur", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Scanline", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Radial Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC DV Fixer", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Median TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Two Way Key OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_SoftFocus", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Color Balance OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Glow Matte OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rays_Streaky MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Cylinder", "BCC Perspective", "Third-party plug-in", {}},
		{"BCC Wooden Planks RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Scatterize TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Lightning", "BCC Lights", "Third-party plug-in", {}},
		{"S_DissolveWaves", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Composite TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_HalfToneColor", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Lens Correction", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Misalignment TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Alpha Pixel Noise OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_WarpWaves", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Wire Remover", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_ReverseEdits", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Fractal Noise", "BCC Textures", "Third-party plug-in", {}},
		{"S_DefocusPrism", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Twirl MT", "BCC Warp", "Third-party plug-in", {}},
		{"S_WipeBubble", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Vector Displacement TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Glint", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Two Strip Color", "BCC Film Style", "Third-party plug-in", {}},
		{"BCC Multi Stripe Wipe OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Textured Wipe OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Sphere Transition", "BCC Perspective", "Third-party plug-in", {}},
		{"BCC Smooth Tone MT", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_DissolveTiles", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_WipePointalize", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Fast Film Glow", "BCC Film Style", "Third-party plug-in", {}},
		{"BCC Match Grain", "BCC Film Style", "Third-party plug-in", {}},
		{"S_BokehLights", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_FilmRoll", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Flutter Cut", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Videoscope", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_Mosaic", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_BleachBypass", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Criss-Cross Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Fast Film Process", "BCC Film Style", "Third-party plug-in", {}},
		{"BCC Fire TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Blur", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Weave RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Brick", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Brick RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Kaleido", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Particle Array 3D", "BCC Particles", "Third-party plug-in", {}},
		{"S_StretchFrameEdges", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_LightLeak", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Rays_Radiant Spotlight MT", "BCC Lights", "Third-party plug-in", {}},
		{"S_VintageColor2Strip", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Glare MT", "BCC Lights", "Third-party plug-in", {}},
		{"S_WipeRings", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Lens Flare 3D MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Lens Flare OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Optical Stabilizer", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Cylinder TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_DissolveRays", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_GlowEdges", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_MathOps", "Sapphire Composite", "Third-party plug-in", {}},
		{"BCC Rock", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Emboss MT", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Colorize", "BCC Color & Tone", "Third-party plug-in", {}},
		{"BCC Light Leaks", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Rays_Ripply", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Spotlight MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Lens Flare TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Grunge", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Clouds RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_EdgeFlash", "Sapphire Composite", "Third-party plug-in", {}},
		{"S_VintageColor3Strip", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Turbulence TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Flicker", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Twister", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Rays_Ring", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Radial Blur TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_EdgeRays", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Pyramid Blur", "BCC Blur", "Third-party plug-in", {}},
		{"S_WipeWedge", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Shape", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Jitter", "BCC Time", "Third-party plug-in", {}},
		{"BCC Organic Strands OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Wooden Planks", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Rays_Textured", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Organic Strands", "BCC Particles", "Third-party plug-in", {}},
		{"BCC Displacement Map TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Lens Flare Advanced TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Lens Flare Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Matte Cleanup", "BCC Key & Blend", "Third-party plug-in", {}},
		{"BCC Tile Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"S_Solarize", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_BlurDirectional", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Cross Glitch", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Bulge", "BCC Warp", "Third-party plug-in", {}},
		{"BCC Criss-Cross Wipe OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_ZGlow", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Grunge", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Sequencer OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Directional Blur", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Artists Poster OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Corner Pin", "BCC Match Move", "Third-party plug-in", {}},
		{"BCC Ripple", "BCC Warp", "Third-party plug-in", {}},
		{"BCC Chroma Key Studio", "BCC Key & Blend", "Third-party plug-in", {}},
		{"BCC Spiral Blur TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_FilmDamage", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Bulge TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Wild Cards TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_DissolveGlow", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Laser Beam", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Make Alpha", "BCC Key & Blend", "Third-party plug-in", {}},
		{"S_Beauty", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"S_PsykoStripes", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_HueSatBright", "Sapphire Adjust", "Third-party plug-in", {}},
		{"S_Monochrome", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Spiral Blur", "BCC Blur", "Third-party plug-in", {}},
		{"S_ZapFrom", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Comet", "BCC Particles", "Third-party plug-in", {}},
		{"S_Transition", "Sapphire Builder", "Third-party plug-in", {}},
		{"BCC Noise Reduction", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_TimeDisplace", "Sapphire Time", "Third-party plug-in", {}},
		{"S_ShowBadColors", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Rays_Cartoon", "BCC Lights", "Third-party plug-in", {}},
		{"S_WarpCornerPin", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_PanAndZoom", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Light Zoom OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Color Choker", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Fast Film Glow Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"S_NearestColor", "Sapphire Time", "Third-party plug-in", {}},
		{"S_DissolveSpeckle", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_TextureNoiseEmboss", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Median", "BCC Art Looks", "Third-party plug-in", {}},
		{"BCC Star Matte TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Twirl TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Z Space I OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Star Matte OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Pin Art 3D OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rays_Radiant Edges", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Rough Glow OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Turbulence", "BCC Warp", "Third-party plug-in", {}},
		{"S_WarpBubble2", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Extruded Spline", "BCC 3D Objects", "Third-party plug-in", {}},
		{"BCC Correct Selected", "BCC Color & Tone", "Third-party plug-in", {}},
		{"BCC Rays_Cartoon MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Multitone", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_Emboss", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Lens Flare 3D TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Grid Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Light Leaks Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"S_DissolveBlur", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_WipeLine", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_DissolveLensFlare", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_FlysEyeHex", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_CartoonPaint", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_TVChannelChange", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_TimeSlice", "Sapphire Time", "Third-party plug-in", {}},
		{"S_StripSlide", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_Grain", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Artists Poster", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_WipeStar", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_GlowDist", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Burnt Film", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC 3D Image Shatter", "BCC Perspective", "Third-party plug-in", {}},
		{"S_FlysEyeRect", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Steel Plate RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_ZFogExponential", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_WipeCircle", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_WarpPuddle", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC HSL", "BCC Color & Tone", "Third-party plug-in", {}},
		{"BCC Light Sweep TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_WarpChroma", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_WarpRepeat", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_CloudsPsyko", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Sphere Transition TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Lens Flash", "BCC Transitions", "Third-party plug-in", {}},
		{"S_RackDefocus", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"S_DogVision", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_MakeRGBA", "Sapphire Composite", "Third-party plug-in", {}},
		{"BCC Alpha Process", "BCC Key & Blend", "Third-party plug-in", {}},
		{"S_TextureSpots", "Sapphire Render", "Third-party plug-in", {}},
		{"S_BlurMotionCurves", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Ripple TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Colorize Glow MT", "BCC Stylize", "Third-party plug-in", {}},
		{"S_GlintRainbow", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_TimeAverage", "Sapphire Time", "Third-party plug-in", {}},
		{"S_ScanLines", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_DissolveFlashbulbs", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Film Damage MT", "BCC Film Style", "Third-party plug-in", {}},
		{"S_WarpDrops", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Pin Art 3D TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_WipeBlobs", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Cross Glitch RT", "BCC Transitions", "Third-party plug-in", {}},
		{"S_ScanLinesMono", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Rays_Wedge MT", "BCC Lights", "Third-party plug-in", {}},
		{"S_GlowRainbow", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Alpha Spotlight OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC 2D Particles TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_DissolveShake", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Gamma", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Z Space III TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rays_Puffy MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Linear Wipe TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Temporal Blur", "BCC Time", "Third-party plug-in", {}},
		{"S_EdgeDetectDouble", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Gaussian Blur OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Vignette Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"S_WipeFlux", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Zap", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Emboss", "BCC Stylize", "Third-party plug-in", {}},
		{"S_EdgesInDirection", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Particle Systems", "BCC Particles", "Third-party plug-in", {}},
		{"S_BlurMotion", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Tritone Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Light Wrap", "BCC Key & Blend", "Third-party plug-in", {}},
		{"BCC Looper", "BCC Time", "Third-party plug-in", {}},
		{"BCC Veined Marble RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Film Grain MT", "BCC Film Style", "Third-party plug-in", {}},
		{"S_ZDefocus", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Multi Shadow", "BCC Stylize", "Third-party plug-in", {}},
		{"S_FlickerMatchColor", "Sapphire Time", "Third-party plug-in", {}},
		{"S_ZFogLinear", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Dropout Fixer", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_Grid", "Sapphire Render", "Third-party plug-in", {}},
		{"S_KaleidoPolar", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC RGB Edges", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC RGB Blend TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Polar Displacement TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_TextureTiles", "Sapphire Render", "Third-party plug-in", {}},
		{"S_MatteOps", "Sapphire Composite", "Third-party plug-in", {}},
		{"BCC Lens Distortion Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Pixel Chooser", "BCC Key & Blend", "Third-party plug-in", {}},
		{"BCC Pan and Zoom", "BCC Perspective", "Third-party plug-in", {}},
		{"BCC Alpha Spotlight OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_ZebrafyColor", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Burnt Film TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Spiral Blur MT", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Cartoon Look", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_Caustics", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Glare", "BCC Lights", "Third-party plug-in", {}},
		{"S_HalfTone", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Levels-Gamma", "BCC Color & Tone", "Third-party plug-in", {}},
		{"BCC Edge Bevel OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Polar Displacement", "BCC Warp", "Third-party plug-in", {}},
		{"BCC Swish Pan", "BCC Transitions", "Third-party plug-in", {}},
		{"S_TextureChromaSpiral", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC RGB Pixel Noise", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Rays Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"S_WarpPerspective", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_TextureNeurons", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Linear Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"S_DigitalDamage", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC 2D Particles", "BCC Particles", "Third-party plug-in", {}},
		{"S_GrainStatic", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_WipePixelate", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_EdgeDetect", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_CloudsVortex", "Sapphire Render", "Third-party plug-in", {}},
		{"S_EmbossDistort", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_Distort", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_FeedbackBubble", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Pyramid Blur MT", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Boost Blend OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Noise Map RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rectangular Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Layer Deformer", "BCC 3D Objects", "Third-party plug-in", {}},
		{"S_BlurChroma", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"S_WipeChecker", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_EdgeBlur", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Rays_Streaky", "BCC Lights", "Third-party plug-in", {}},
		{"BCC FX Browser", "BCC Browser", "Third-party plug-in", {}},
		{"S_TextureNoisePaint", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Lens Shape MT", "BCC Blur", "Third-party plug-in", {}},
		{"BCC Steel Plate", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Lens Transition TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Time Displacement", "BCC Time", "Third-party plug-in", {}},
		{"BCC Page Turn TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Glitter", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Radial Wipe OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Spraypaint Noise", "BCC Art Looks", "Third-party plug-in", {}},
		{"BCC Laser Beam MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Rays_Ripply MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Halftone", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_Retime", "Sapphire Time", "Third-party plug-in", {}},
		{"S_ZBlur", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Jitter Basic", "BCC Time", "Third-party plug-in", {}},
		{"BCC Veined Marble", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Composite OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Composite Choker", "BCC Key & Blend", "Third-party plug-in", {}},
		{"S_TextureFolded", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Match Move", "BCC Match Move", "Third-party plug-in", {}},
		{"BCC Video Glitch", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Tritone OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Weave", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Mosaic", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Type On Text", "BCC 3D Objects", "Third-party plug-in", {}},
		{"BCC Noise Map 2 TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rays_Puffy", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Granite", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Prism", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Posterize Time", "BCC Time", "Third-party plug-in", {}},
		{"BCC Stars", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Fire OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Halftone TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Rectangular Wipe TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Color Correction", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_DuoTone", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Reptilian", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Cartooner", "BCC Art Looks", "Third-party plug-in", {}},
		{"BCC Wild Cards", "BCC Particles", "Third-party plug-in", {}},
		{"S_ZComp", "Sapphire Composite", "Third-party plug-in", {}},
		{"S_Clouds", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Linear Luma Key", "BCC Key & Blend", "Third-party plug-in", {}},
		{"S_CloudsPerspective", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Cross Zoom", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Super Blend OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_CutToDissolve", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Reverse Spotlight", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Composite Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"S_Feedback", "Sapphire Time", "Third-party plug-in", {}},
		{"BCC Particle Array 3D OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Sparks MT", "BCC Particles", "Third-party plug-in", {}},
		{"S_RackDfComp", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Tritone", "BCC Color & Tone", "Third-party plug-in", {}},
		{"S_Hotspots", "Sapphire Adjust", "Third-party plug-in", {}},
		{"S_TextureMicro", "Sapphire Render", "Third-party plug-in", {}},
		{"S_DissolveStatic", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC LED", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Glint MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Deinterlace", "BCC Film Style", "Third-party plug-in", {}},
		{"BCC DVE TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Multi Stretch Wipe OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_GlowOrthicon", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_Effect", "Sapphire Builder", "Third-party plug-in", {}},
		{"BCC Particle Emitter 3D TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_ClampChroma", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Cloth", "BCC Textures", "Third-party plug-in", {}},
		{"BCC Colorize Glow TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_FilmEffect", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Vignette", "BCC Film Style", "Third-party plug-in", {}},
		{"BCC Pixel Chooser OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Smooth Tone", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_TileScramble", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_FlickerMchMatteColor", "Sapphire Time", "Third-party plug-in", {}},
		{"S_DissolveDistort", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Granite RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Median", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Charcoal Sketch", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_DissolveDefocus", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Crosshatch", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Blur Dissolve", "BCC Transitions", "Third-party plug-in", {}},
		{"BCC Rings Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"S_GetFrame", "Sapphire Time", "Third-party plug-in", {}},
		{"S_WarpMagnify", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC Pencil Sketch", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_Glare", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_ConvolveComp", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Light Matte OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Light Zoom TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Stage Light", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Linear Color Key", "BCC Key & Blend", "Third-party plug-in", {}},
		{"BCC Reframer", "BCC Image Restoration", "Third-party plug-in", {}},
		{"S_TexturePlasma", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Light Sweep", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Lens Flare Spiked", "BCC Transitions", "Third-party plug-in", {}},
		{"S_DissolveLuma", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Etching", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Glow Alpha Edges", "BCC Stylize", "Third-party plug-in", {}},
		{"S_WipeDots", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Z Space I TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_GlowNoise", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_Light3D", "Sapphire Lighting", "Third-party plug-in", {}},
		{"S_ChannelSwitcher", "Sapphire Adjust", "Third-party plug-in", {}},
		{"BCC Wave", "BCC Warp", "Third-party plug-in", {}},
		{"BCC Color Correction OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"Titler Pro 4", "NewBlue Titler Pro 4", "Third-party plug-in", {}},
		{"BCC Water Color", "BCC Art Looks", "Third-party plug-in", {}},
		{"S_FlickerMatchMatte", "Sapphire Time", "Third-party plug-in", {}},
		{"S_Convolve", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"S_SparklesColor", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Directional Blur TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Criss-Cross Wipe TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Glint", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Snow", "BCC Particles", "Third-party plug-in", {}},
		{"BCC Median MT", "BCC Art Looks", "Third-party plug-in", {}},
		{"BCC Twirl", "BCC Warp", "Third-party plug-in", {}},
		{"S_FlickerRemoveMatte", "Sapphire Time", "Third-party plug-in", {}},
		{"S_Aurora", "Sapphire Render", "Third-party plug-in", {}},
		{"S_Vignette", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Posterize OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Glow Matte TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Gradient", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Lens Flare Advanced OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Bump Map RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Glow", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Chroma Key", "BCC Key & Blend", "Third-party plug-in", {}},
		{"BCC Fast Flipper", "BCC Perspective", "Third-party plug-in", {}},
		{"BCC Brightness Contrast", "BCC Color & Tone", "Third-party plug-in", {}},
		{"BCC Rain", "BCC Particles", "Third-party plug-in", {}},
		{"S_WarpToRect", "Sapphire Distort", "Third-party plug-in", {}},
		{"BCC RGB Blend", "BCC Key & Blend", "Third-party plug-in", {}},
		{"BCC Brightness Contrast OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Wild Cards OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_DropShadow", "Sapphire Lighting", "Third-party plug-in", {}},
		{"BCC Multi Stretch Wipe TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_DissolveBubble", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_RepairFrames", "Sapphire Time", "Third-party plug-in", {}},
		{"S_RandomEdits", "Sapphire Time", "Third-party plug-in", {}},
		{"S_Posterize", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Multi Stripe Wipe TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_ZapTo", "Sapphire Render", "Third-party plug-in", {}},
		{"S_TextureMoire", "Sapphire Render", "Third-party plug-in", {}},
		{"BCC Tile Mosaic", "BCC Art Looks", "Third-party plug-in", {}},
		{"BCC Wire Remover MT", "BCC Image Restoration", "Third-party plug-in", {}},
		{"BCC Glow OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_Diffuse", "Sapphire Stylize", "Third-party plug-in", {}},
		{"S_WarpWaves2", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_WipeMoire", "Sapphire Transitions", "Third-party plug-in", {}},
		{"S_Shake", "Sapphire Distort", "Third-party plug-in", {}},
		{"S_Cartoon", "Sapphire Stylize", "Third-party plug-in", {}},
		{"BCC Damaged TV", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Emboss RT Static OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"BCC Gaussian Blur TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
		{"S_WipeClouds", "Sapphire Transitions", "Third-party plug-in", {}},
		{"BCC Reverse Spotlight MT", "BCC Lights", "Third-party plug-in", {}},
		{"BCC Multi Stripe Wipe", "BCC Transitions", "Third-party plug-in", {}},
		{"S_BlurChannels", "Sapphire Blur+Sharpen", "Third-party plug-in", {}},
		{"BCC Color Choker MT", "BCC Stylize", "Third-party plug-in", {}},
		{"BCC Organic Strands TR OBS", "BCC Obsolete", "Third-party plug-in", {}},
	};

	struct Row
	{
		QString name;
		QString category;
	};

	struct Table
	{
		QVector<Row> rows;
		QHash<QString, QVector<int>> byKey; ///< mangled name (any language) → rows
	};

	/// Built once, on first use, from the compiled-in catalogue: ~890 names
	/// mangled and hashed, a few milliseconds. The table itself costs nothing
	/// to load — it is string literals in the binary, not a file to find.
	const Table &table()
	{
		static const Table t = []
		{
			Table out;
			out.rows.reserve(std::size(kEffects));
			for (const Entry &e : kEffects)
			{
				const int idx = out.rows.size();
				out.rows.append({QString::fromUtf8(e.name), QString::fromUtf8(e.category)});
				// English name, then every localised spelling Avid ships.
				QSet<QString> keys{AvidEffects::mangle(out.rows[idx].name)};
				for (const char *localised : e.localised)
					if (localised && *localised)
						keys.insert(AvidEffects::mangle(QString::fromUtf8(localised)));
				for (const QString &k : keys)
					out.byKey[k].append(idx);
			}
			return out;
		}();
		return t;
	}
} // namespace

QString AvidEffects::mangle(const QString &displayName)
{
	QString s = displayName;
	s.replace(QLatin1Char(' '), QLatin1Char('_'));
	s.replace(QLatin1Char(':'), QLatin1Char('_'));
	return s;
}

int AvidEffects::size()
{
	return table().rows.size();
}

AvidEffects::Hit AvidEffects::lookup(const QString &clipName)
{
	Hit hit;
	// Both observed render names keep the effect at the right-hand end:
	// `<sequence>,<Effect>+<N>` and `<sequence>,<Effect>,<N>[.new.<N>...]`.
	// Validate the latter's entire numeric suffix before using the preceding
	// comma; earlier commas still belong to the sequence. This labels only
	// already-classified precomputes and does not identify media by name.
	QString token = clipName;
	const int comma = clipName.lastIndexOf(QLatin1Char(','));
	if (comma >= 0)
	{
		hit.sequence = clipName.left(comma);
		token = clipName.mid(comma + 1);
	}
	bool commaInstance = false;
	static const QRegularExpression kCommaInstance(QStringLiteral("\\A[0-9]+(?:\\.new\\.[0-9]+)*\\z"));
	if (comma > 0 && kCommaInstance.match(token).hasMatch())
	{
		const int effectComma = clipName.lastIndexOf(QLatin1Char(','), comma - 1);
		if (effectComma >= 0 && effectComma + 1 < comma)
		{
			const QStringList numbers = token.split(QStringLiteral(".new."));
			bool valid = true;
			int instance = 0;
			for (qsizetype i = 0; i < numbers.size(); ++i)
			{
				bool ok = false;
				const int value = numbers[i].toInt(&ok);
				if (!ok)
				{
					valid = false;
					break;
				}
				if (i == 0)
					instance = value;
			}
			if (valid)
			{
				hit.sequence = clipName.left(effectComma);
				token = clipName.mid(effectComma + 1, comma - effectComma - 1);
				hit.instance = instance;
				commaInstance = true;
			}
		}
	}
	if (!commaInstance)
	{
		static const QRegularExpression kInstance(QStringLiteral("\\+([0-9]+)\\z"));
		const QRegularExpressionMatch m = kInstance.match(token);
		if (m.hasMatch() && m.capturedStart(0) > 0)
		{
			bool ok = false;
			const int instance = m.captured(1).toInt(&ok);
			if (ok)
			{
				hit.instance = instance;
				token.chop(m.capturedLength(0));
			}
		}
	}

	const Table &t = table();
	const auto it = t.byKey.constFind(token);
	if (it == t.byKey.constEnd() || it->isEmpty())
	{
		hit.name = token;
		hit.category = QStringLiteral("Not a standard Avid effect");
		return hit;
	}
	hit.matched = true;
	hit.name = t.rows[it->first()].name;
	// One name can live in several palette groups ("Bottom to Top" is a
	// Conceal, a Peel, a Push and a Squeeze); say all of them, in file order.
	QStringList categories;
	for (int idx : *it)
		if (!categories.contains(t.rows[idx].category))
			categories << t.rows[idx].category;
	hit.category = categories.join(QStringLiteral(" / "));
	return hit;
}
